### ISSUE TITLE
KsnProfiler: Problems Saving Large Datasets

### ISSUE THREAD

**Issue by kxwhipple** [amforte/Topographic-Analysis-Kit#12]
When working with large datasets, KsnProfiler will issue this Warning for some versions of Matlab:
"Variable 'input_params' was not saved. For variables larger than 2GB use MAT-file version 7.3 or later."
In this case, at the end of the process, KsnProfiler will crash as it fails to save the data.

Adam is aware of the problem and will soon fix this. In the meantime he points out that users can avoid this (if it occurs with their version of Matlab) by setting *.mat files to be saved as v7.3 by default in their matlab settings.

**Comment by amforte** [comment]
This has been fixed in both matlab and compiled versions now.
