### ISSUE TITLE
ksn chi batch misnamed in the header to document the issue

### ISSUE THREAD

**Issue by amitneotectonic** [amforte/Topographic-Analysis-Kit#13]
The example given in the function is following:
Example:
	%	KSN_Chi_Batch(DEM,FD,A,S,'ksn');
	%	[KSN,ChiMap,ChiGrid]=KSN_Chi_Batch(DEM,FD,A,S,'output',true,'theta_ref',0.55);

However, the name of function is **KsnChiBatch.** Therefore, when using example, Please change the function name to KsnChiBatch. 

thanks

cheers-
Amit
Nepal

**Comment by amforte** [comment]
Correction is made and will be included in next update.
