### ISSUE TITLE
Error saving output of KsnChiBatch to Matlab workspace

### ISSUE THREAD

**Issue by jessezondervan** [amforte/Topographic-Analysis-Kit#16]
When running the KsnChiBatch I get an error when the code tries to save to the Matlab workspace:

> Undefined function or variable 'KSN'.
> 
> Error in KsnChiBatch (line 342)
> 			varargout{2}=KSN;

This is the parameters with which I ran the tool:

> [KSN_STREAM_GRID, ksn_ms , KSN_GRID , CHI_MAP, CHI_GRID]=KsnChiBatch (DEM,FD,A, S , 'all',...
>     'ref_concavity', 0.44, 'ksn_method', 'trib', 'outlet_level_method', 'elevation',...
>     'min_elevation', 1380,'output', true);

Best,

Jesse

**Comment by amforte** [comment]
Error is corrected and will be included in next update.
