### ISSUE TITLE
KsnChiBatch: ksn grid with edge effect

### ISSUE THREAD

**Issue by jessezondervan** [amforte/Topographic-Analysis-Kit#17]
The output of the Ksn grid gives me an edge effect (see attachment).
![failedksngrid](https://user-images.githubusercontent.com/36923725/44213199-0d32c500-a165-11e8-98c5-3013bd801282.PNG)

**Comment by jessezondervan** [comment]
Clipping the KsnGrid to the DEM shape solves this issue

![ksngrid_clipped](https://user-images.githubusercontent.com/36923725/44216343-9699c580-a16c-11e8-87aa-f8568710c32b.PNG)

**Comment by amforte** [comment]
I've added a step to crop out any areas that are NaN in the original DEM in the resulting interpolated ksn grid. This will be included in the next update.
