### ISSUE TITLE
CompileBasinStats description same as Basin2Shape

### ISSUE THREAD

**Issue by jessezondervan** [amforte/Topographic-Analysis-Kit#20]
I suspect that the description for Basin2Shape has been copied into the CompileBasinStats. It states CompileBasinStats produces a shapefile, while the guide specifies a table will be the output. 

Best,

Jesse

**Comment by jessezondervan** [comment]
Just noticed a typo in the description. Usage says

`[MapStruct]=Basin2Sahpe(DEM,location_of_data_files);``

should be

`[MapStruct]=Basin2Shape(DEM,location_of_data_files);`

**Comment by amforte** [comment]
Both headers have been updated and will be included in the next update.
