### ISSUE TITLE
MakeCombinedSwath: error with ksn_batch

### ISSUE THREAD

**Issue by jessezondervan** [amforte/Topographic-Analysis-Kit#21]
Trying to run:

`>> [SW,SwathMat,xypoints,outData]=MakeCombinedSwath(DEM,Swath1,15000,'ksn_batch',KSN,15000);
`
gives me

```
Index exceeds array bounds.

Error in MakeCombinedSwath (line 512)
				xx=mean(data(kk,1).X);
```

**Comment by amforte** [comment]
Please confirm which output from KsnChiBatch you provided (i.e. what is 'KSN' in the example you posted). It's expecting the geographic data structure, so the second output if you ran KsnChiBatch with either 'ksn' or 'all' as the product.

**Comment by amforte** [comment]
This error was fixed.
