### ISSUE TITLE
Error: Not enough arguments. Error in => TAK.m at line 9.

### ISSUE THREAD

**Issue by ibnsana** [amforte/Topographic-Analysis-Kit#22]
I tried to install TAK for Toptoolbox  from "Windows" folder "InstallTAKandMatlabRuntime.exe". I get the following error: 

Not enough arguments. Error in => TAK.m at line 9.

**Comment by amforte** [comment]
This happens if you try to run TAK by clicking on its icon in the Program Files, but as described in the user manual, you need to run the compiled version of TAK from the command line (see user manual for more detailed description).
