### ISSUE TITLE
Compiled Functions Do Not Fully Complete

### ISSUE THREAD

**Issue by amforte** [amforte/Topographic-Analysis-Kit#23]
At present, running the compiled version of the functions will successfully complete (i.e. the desired outputs will be produced and a message saying that the function successfully completed will display) but the code remains engaged after this and the command prompt doesn't return. This can be solved by pressing ctrl-c to get back to the command prompt and continue with any desired TAK functions, but I'm looking into a more permanent fix so that the command prompt will reappear after successful completion.

**Comment by Ron-Wang** [comment]
Excuse me, where can l download ExampleData.tar.gz?

**Comment by Ron-Wang** [comment]
Excuse me, how can I download Example.tar.gz? 
When I use my .tif file, it shows error("the value of 'dem' is invalid "). So, I want to use the example file to test.

**Comment by Ron-Wang** [comment]
Thanks~
I have found it.
