### ISSUE TITLE
How can I transform my .tif file of FD to FLOWobj, .shp of S to STREAMobj?

### ISSUE THREAD

**Issue by Ron-Wang** [amforte/Topographic-Analysis-Kit#28]

**Comment by amforte** [comment]
There is not a straight forward way to convert a flow direction raster or stream network produced in another program (e.g. ArcGIS) into a FLOWobj or STREAMobj. You need to generate FLOWobjs and STREAMobjs within TAK (or TopoToolbox).

**Comment by gzm456** [comment]
I have some problems when using 'MakeCombinedSwath' tools,can u show some examples about code

**Comment by amforte** [comment]
This is not enough information to answer your question. There are a lot of options in MakeCombinedSwath, so you’ll need to provide more detail. What kind of data were you trying to project? If you got an error message, what was it? Etc. There are some limited examples in the manual, but it’s not practical to provide examples for every possible use case for every function.

Adam M. Forte
Assistant Professor
Department of Geology & Geophysics
Louisiana State University
############################
Sent from my mobile
________________________________
