### ISSUE TITLE
ASking for help

### ISSUE THREAD

**Issue by 098alex** [amforte/Topographic-Analysis-Kit#29]
i have installed the TAK , but when i double cilcked it,there is a   small popup dialog like this 
![image](https://user-images.githubusercontent.com/48704058/54578617-591b5480-4a3b-11e9-9ae9-5642920b9578.png),and i just dont know how to deal with it,could you give me a hand?

@amforte

**Comment by amforte** [comment]
As described in the user manual, you need to run the compiled version from a terminal window (command prompt on Windows, terminal on Mac). Refer to the section in the manual on the compiled versions and the appendix for help on calling specific functions.
On Mon, Mar 18, 2019 at 10:40 PM 098alex <notifications@github.com<mailto:notifications@github.com>> wrote:

i have installed the TAK , but when i double cilcked it,there is a small popup dialog like this
[image]<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F48704058%2F54578617-591b5480-4a3b-11e9-9ae9-5642920b9578.png&data=02%7C01%7Caforte8%40lsu.edu%7C1852e632a7684eeb505708d6ac1ca57f%7C2d4dad3f50ae47d983a09ae2b1f466f8%7C0%7C0%7C636885636363716701&sdata=G3GwJimddNj5TYJtZu3kpNaG%2FjB78fDVRdgKa5Brx%2B8%3D&reserved=0>,and i just dont know how to deal with it,could you give me a hand?

@amforte<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Famforte&data=02%7C01%7Caforte8%40lsu.edu%7C1852e632a7684eeb505708d6ac1ca57f%7C2d4dad3f50ae47d983a09ae2b1f466f8%7C0%7C0%7C636885636363716701&sdata=19oiEtQnOVo8%2BG%2BYQ9idszSMdH3v4%2FRenr3n2IN9SpY%3D&reserved=0>
