### ISSUE TITLE
Manually choosing knickpoints with ksn profiler

### ISSUE THREAD

**Issue by abn-codes** [amforte/Topographic-Analysis-Kit#33]
Hey Adam, we have a project where we would like to manually identify the bounds of waterfalls along certain selected stream profiles.  

The knickpoint selection tool I see in the KsnProfiler (ClassifyKnicks) selects knickpoints between selected segments. While good for slope-break knickpoints, these waterfalls do not necessarily make segment boundaries between distinct ksn profiles.  Many of the waterfalls lie within a stream segment that we're measuring the Ksn over.  We're interested in the gradient/relief of the total reach, but also the % of the relief within that reach that is taken up by distinct waterfall steps. 

In the old profiler toolbar, you could select knickpoints anywhere on the longitudinal profile, and these points were saved as shapefiles with the knickpoint metrics. 

Is there an option like this in TAK?

I explored the 'FindBasinKnicks' command too, but this seems cumbersome, because you can't select segments here (unlike the profiler tool), and you have to run through all of the tributaries within the basin you're analyzing. Also, it looks like you have to do the knickpoint picking here on the chi plot (which you can hack into a distance-elevation plot setting the ref_conc to 0, but still may not be ideal). Also if you're analyzing profiles across multiple basins, you have to re-write your 'FindBasinKnicks' command to update the path to the Basin_x_data.mat file.  

Do you have suggestions on routines in TAK to use to do this? or is the old profiler toolbar still the way to go to pick out the bounds of these 'discrete channel step' knickpoints manually?

Thanks,

-Al

**Comment by amforte** [comment]
In short, no. There's not an option like this at present, but it would make sense to add one. An interim kludge solution would be to pick knickpoints in KsnProfiler (even if they do not define distinct segments) so you can then classify them later. In the future though, I will try to add something to KsnProfiler that will allow you to select a non-segment knickpoint.

**Comment by amforte** [comment]
I've implemented a version of this that works with KsnProfiler and ClassifyKnicks. Now, with the crosshairs on a stream if you press any mouse button or keyboard button other than the left mouse button (or enter), this will log this position as a feature but not a bound for a ksn segment. These are stored in a separate file that is also passed to ClassifyKnicks and can be classified along with the bounds (they are displayed as different symbols in ClassifyKnicks so you know which is which).
