### ISSUE TITLE
Multiple segment projections

### ISSUE THREAD

**Issue by Hohmann88** [amforte/Topographic-Analysis-Kit#39]
Hi Adam,
is or will there be a possibility to project more than one segment using SegmentProjector or any other function? I know that you can select different segments with KSNProfiler but you cant project them...
Best Regards, Konstantin

**Comment by amforte** [comment]
SegmentProjector by default expects you will project ALL streams passed to it (with the number of streams being determined by the number of channel heads). This is why the recommended pathway is to use SegmentPicker to select out the streams you want to project and then provide that set of streams as the input to SegmentProjector.

**Comment by Hohmann88** [comment]
apologies for my unclear use of terminology. With "segments" i was referring to different portions of a single stream for example regressed with slope-area-plot or chi-plot. some streams flow through (2-3) different elevated low-relief landscapes and thus only one projection would not suffice. I hope this is now clearer. BR, Konstantin

**Comment by amforte** [comment]
Ah, yeah. At present, SegmentProjector is not set up to do that. One of my students has been working on an alternative version for this very purpose, but it's not quite ready for prime time yet. In the interim, the easiest way to do this would be simply to run SegmentProjector multiple times. If you are doing this on the same set of streams, then outside of TAK, it would then be possible to difference these different projections if you are interested in multiple different incision events and the variability between them.

**Comment by Hohmann88** [comment]
ok, thats unfortunate. An implementation of multiple projections would probably be much appreciated by the community. 
I will close this issue.
