### ISSUE TITLE
Add more outputs attributes in KnickTable - FindBasinKnicks

### ISSUE THREAD

**Issue by GenissonPanta** [amforte/Topographic-Analysis-Kit#41]
Hi, Adam!

I'm would like of add more outputs in my KnickTable, but I haven't ideia of how to do that. For exemple, I want add Drainage Area, Slope and Ksn values in rowns inside of KnickTable beyond of default (Chi, Elevation, Distance, Xcoord, Ycoord). I haven't experience in programming, so this is the reason of my question.

Greetings from Brazil!

**Comment by amforte** [comment]
Drainage area is pretty easy to query using TopoToolbox:

% Generate drainage area raster
DA=A.*A.cellsize^2;
% Generate index from KnickTable output from FindBasinKnicks and query
ix=coord2ind(DEM,KnickTable.x_coord,KnickTable.y_coord);
da=DA.Z(ix);

Slope and ksn are more complicated as it comes down to what the appropriate values are. Do you want the ksn and slope right at the knickpoint? Knickpoints theoretically define areas where ksn / slope change so do you want upstream? downstream? difference? average? Querying those values is non-trivial and the procedure would be different depending on what value you actually want.

**Comment by GenissonPanta** [comment]
Thanks! 

This was userful for my reseach. Beyond this, I want add ksn and slope exactly on knickpoint, but the drainage area already helped me a lot.

**Comment by amforte** [comment]
Ok, I think it will be difficult to interpret these values from the knickpoints, but assuming you have the same 'ix' output from the block of text above, you could do this to get these values:

% Generate KSN grid and extract ksn values
[KSNG,~]=KsnChiBatch(DEM,FD,A,S,'ksn','output',true); % Plus whatever options you need
ksn_at_knicks=KSNG.Z(ix);

% Calculate gradient along stream network and populate an empty raster
g=gradient(S,DEM);
G=GRIDobj(DEM);
G.Z(S.IXgrid)=g;

% Extract slopes from the knickpoints
g_at_knicks=G.Z(ix);

I'm going to go ahead and close this issue.
