### ISSUE TITLE
Brush Data

### ISSUE THREAD

**Issue by amforte** [amforte/Topographic-Analysis-Kit#47]
Hi,
After loading .mat file of DEM in GUI, I ran 'Segment Picker'. The output was in vector format where used 'Brush/Select Data' for selecting stream segments. Segments were selected (marked in red).  My question is 'how do I make mat file containing StreamOBJs after selecting segments.' I cannot find further step to proceed. 
![Issue](https://user-images.githubusercontent.com/77884720/105578612-7e035000-5da7-11eb-8664-51a18cfa4fa3.JPG)

Help would be appreciated. Thanks.

_Originally posted by @hitander in https://github.com/amforte/Topographic-Analysis-Kit/issues/35#issuecomment-765979921_

**Comment by amforte** [comment]
@hitander 

Could you clarify, did you use the built in functionality of SegmentPicker to select streams or bypass this and use brush data to select streams?

**Comment by hitander** [comment]
I used Segment Picker itself to select the streams. It opens a window of
DEM with streams. Then I used brush data to select streams.

**Comment by hitander** [comment]
> @hitander
> 
> Could you clarify, did you use the built in functionality of SegmentPicker to select streams or bypass this and use brush data to select streams?


https://user-images.githubusercontent.com/77884720/105589500-cfb3d680-5db7-11eb-8ab8-1757b5dd898a.mp4




Here is a clip for clarification. Clip is up to the end of steps which I am trying. I am unable to perform any steps further.

**Comment by amforte** [comment]
Yes, you are not using the internal SegmentPicker function, you are using the brush data. As the instructions that appear at the top of the window tell you, after you've zoomed in or out (or not) press enter on you keyboard and a set of crosshairs appear. This is how the code expects you to select streams. As you go through this process it will ask you if you want to continue with a yes no dialog box. When you tell it stop, a mat file will be generated with the selected streams as a STREAMobj inside.

Please consult the tutorial presentations / files as well if you need additional help.

**Comment by hitander** [comment]
A set of crosshair is not appearing. That's why I used brush data.  
When the function says "return/enter', I hit enter but nothing happens. I waited for several minutes for "return/enter' to pop up something. I have tried the same method numerous times and not able to proceed. Kindly suggest.

**Comment by amforte** [comment]
Is the popup window (i.e. the window displaying the DEM and stream network) selected as the active window when you press enter or return? I've tested this on both a mac and PC and haven't had any issue with it not recognizing an enter/return press as long as the map window (as opposed to the main GUI window) is active so no, I don't have any alternative suggestions. Is this the standalone GUI or the App running inside Matlab?

**Comment by hitander** [comment]
Yes, the popup window is selected while performing the "enter/return"
operation. One of my friends has also tried the same option and we both are
facing the same techical issue.
The problem is occuring on the App running inside Matlab.

**Comment by amforte** [comment]
And you're using what version of Matlab?

**Comment by hitander** [comment]
It's Matlab 2013R. The same issue also occurs on ksnProfiler.

**Comment by amforte** [comment]
Ok, so it's likely a (Matlab) version issue if I had to guess. The GUI (and most of the underlying TAK functions) were designed on Matlab 2017 and greater. I've never tested these on versions of Matlab earlier than 2017. I've run multiple short courses and so have seen these functions run on a variety of different machines (so I'm pretty sure it's not a bug), but never on any version of matlab that far out of date. 

I think you have three options:

(1) You could try running these codes outside of the GUI, i.e. use the native TAK functions in Matlab. There's a chance that maybe these will work better and that the issue lies with the way the GUI is interpreted by much older versions of Matlab.

(2) If you're able, you could try updating Matlab.

(3) If option 1 doesn't work and option 2 isn't viable, then you could installing the standalone gui with the correct Matlab Runtime Environment installed.

**Comment by hitander** [comment]
Ok. I'll try these. I hope one of them works. Thank you very much!!
